### ISSUE TITLE
Stream Feedback: center-of-mass/dV problem in the editor

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/ModularSegmentedSRBs#1]
For solving SRB's center-of-mass/dV problem I belive you could use massless fuel. 

the "first fuel" is massless and invisible, that is always moved into an engine for calculating dV, and maybe even not continuously at flight, but at once, in the editor and flight at time of vessel_changed_in_the_editor() and vessel_is_loaded_to_flight().

the "second fuel" has mass, for the right center of mass, and for showing to user what tank has fuel. Tank without fuel, which behave as it has fuel, is frustrating.
An engine doesn't have the second fuel, only tanks.

Only problem is is center of mass in flight. The second fuel need to sink in flight. And the second will sink to nowhere, because for the burn and dV the first fuel is used.

**Comment by linuxgurugamer** [comment]
I would have to check, but the mass of the fuel may contribute to the ISP & dV calculations.
Shouldn't be that difficult to test

**Comment by yalov** [comment]
Another request is to have separate nosecones for every size, like the tanks (for consistency), 
and leave nosecone variants for the future (maybe for a different shape of the nosecone, or for the built-in 1-2-3m solid fuel tank in the nosecone)

**Comment by linuxgurugamer** [comment]
There are two nosecones, each can be resized using PartVariants.

I'm trying to keep the total part count down, there is already an overabundance of parts available

**Comment by linuxgurugamer** [comment]
when I release a beta, I'll ask for feedback about the parts

**Comment by linuxgurugamer** [comment]
Testing has shown the following:

I set the burnable fuel's density to 0.00 to give it no mass

In the editor, using a single segment with a motor, the ISP looked ok, the thrust looked ok, but the burn time was 4404 seconds. 

Same parts, with the fuel density set correctly, the burn time was 33s

Good idea, but it just won't work properly

**Comment by yalov** [comment]
strange that burn-time relates to mass, and doesn't just equals to amount_of_fuel/engine_consumption

**Comment by linuxgurugamer** [comment]
Burn time relates to the thickness of the SRB.  Thrust relates to the length
